/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Cursor;

/**
 *
 * @author USER
 */
public class CreateClassView extends javax.swing.JPanel {

    /**
     * Creates new form CreateAccountView
     */
    public CreateClassView() {
        initComponents();
        
        //Setting cursor pointer
        Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        crtAccountLink.setCursor(cursor);
        backBtn.setCursor(cursor);
        createNewAccBtn.setCursor(cursor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeUserBtnGroup = new javax.swing.ButtonGroup();
        crtAccountLink = new javax.swing.JLabel();
        txtLabel = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        LogoImgPanel = new javax.swing.JPanel();
        imgWrapperLabel = new javax.swing.JLabel();
        CrtAccountFormPanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        teacherField = new javax.swing.JTextField();
        teacherLabel = new javax.swing.JLabel();
        subjectField = new javax.swing.JTextField();
        subjectLabel = new javax.swing.JLabel();
        totalOfExamsLabel = new javax.swing.JLabel();
        totalOfExamsField = new javax.swing.JPasswordField();
        confirmPswField = new javax.swing.JPasswordField();
        selectLabel = new javax.swing.JLabel();
        minAverAppLabel = new javax.swing.JLabel();
        weightedOptBtn = new javax.swing.JRadioButton();
        normalOptBtn = new javax.swing.JRadioButton();
        createNewAccBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JLabel();
        examsComboBox = new javax.swing.JComboBox<>();
        chooseExamLabel = new javax.swing.JLabel();
        weightField = new javax.swing.JTextField();
        weightLabel = new javax.swing.JLabel();

        crtAccountLink.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        crtAccountLink.setForeground(new java.awt.Color(88, 44, 169));
        crtAccountLink.setText("Create an Account");
        crtAccountLink.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtLabel.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtLabel.setForeground(new java.awt.Color(0, 0, 0));
        txtLabel.setText("Not registered yet?");

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 873));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        LogoImgPanel.setBackground(new java.awt.Color(255, 255, 255));

        imgWrapperLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/crtClassLogoImg.png"))); // NOI18N
        imgWrapperLabel.setPreferredSize(new java.awt.Dimension(496, 873));

        javax.swing.GroupLayout LogoImgPanelLayout = new javax.swing.GroupLayout(LogoImgPanel);
        LogoImgPanel.setLayout(LogoImgPanelLayout);
        LogoImgPanelLayout.setHorizontalGroup(
            LogoImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgWrapperLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LogoImgPanelLayout.setVerticalGroup(
            LogoImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgWrapperLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CrtAccountFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        loginLabel.setFont(new java.awt.Font("Arial", 0, 44)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(42, 8, 69));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Create a class");

        nameField.setBackground(new java.awt.Color(159, 107, 255));
        nameField.setBorder(null);
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(42, 8, 69));
        nameLabel.setText("Name:");

        teacherField.setBackground(new java.awt.Color(159, 107, 255));
        teacherField.setBorder(null);
        teacherField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherFieldActionPerformed(evt);
            }
        });

        teacherLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        teacherLabel.setForeground(new java.awt.Color(42, 8, 69));
        teacherLabel.setText("Teacher:");

        subjectField.setBackground(new java.awt.Color(159, 107, 255));
        subjectField.setBorder(null);
        subjectField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectFieldActionPerformed(evt);
            }
        });

        subjectLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        subjectLabel.setForeground(new java.awt.Color(42, 8, 69));
        subjectLabel.setText("Subject:");

        totalOfExamsLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        totalOfExamsLabel.setForeground(new java.awt.Color(42, 8, 69));
        totalOfExamsLabel.setText("Total of Exams:");

        totalOfExamsField.setBackground(new java.awt.Color(160, 108, 255));
        totalOfExamsField.setBorder(null);

        confirmPswField.setBackground(new java.awt.Color(160, 108, 255));
        confirmPswField.setBorder(null);

        selectLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        selectLabel.setForeground(new java.awt.Color(42, 8, 69));
        selectLabel.setText("Select the averange calculous:");

        minAverAppLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        minAverAppLabel.setForeground(new java.awt.Color(42, 8, 69));
        minAverAppLabel.setText("Minimum averange for approvement:");

        weightedOptBtn.setBackground(new java.awt.Color(40, 20, 77));
        typeUserBtnGroup.add(weightedOptBtn);
        weightedOptBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        weightedOptBtn.setForeground(new java.awt.Color(40, 20, 77));
        weightedOptBtn.setText("Weighted Average");
        weightedOptBtn.setBorder(null);
        weightedOptBtn.setOpaque(false);
        weightedOptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightedOptBtnActionPerformed(evt);
            }
        });

        normalOptBtn.setBackground(new java.awt.Color(40, 20, 77));
        typeUserBtnGroup.add(normalOptBtn);
        normalOptBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        normalOptBtn.setForeground(new java.awt.Color(40, 20, 77));
        normalOptBtn.setText("Normal");
        normalOptBtn.setBorder(null);
        normalOptBtn.setOpaque(false);
        normalOptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalOptBtnActionPerformed(evt);
            }
        });

        createNewAccBtn.setBackground(new java.awt.Color(88, 44, 169));
        createNewAccBtn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        createNewAccBtn.setForeground(new java.awt.Color(255, 255, 255));
        createNewAccBtn.setText("CREATE NEW");
        createNewAccBtn.setBorder(null);
        createNewAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewAccBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        backBtn.setForeground(new java.awt.Color(88, 44, 169));
        backBtn.setText("Back");
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        examsComboBox.setBackground(new java.awt.Color(160, 108, 255));
        examsComboBox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        examsComboBox.setForeground(new java.awt.Color(255, 255, 255));
        examsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class 1", "Class 2", "Class 3", "Class 4" }));
        examsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examsComboBoxActionPerformed(evt);
            }
        });

        chooseExamLabel.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        chooseExamLabel.setForeground(new java.awt.Color(42, 8, 69));
        chooseExamLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chooseExamLabel.setText("Choose an exam:");

        weightField.setBackground(new java.awt.Color(160, 108, 255));
        weightField.setBorder(null);

        weightLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        weightLabel.setForeground(new java.awt.Color(42, 8, 69));
        weightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        weightLabel.setText("Weight:");

        javax.swing.GroupLayout CrtAccountFormPanelLayout = new javax.swing.GroupLayout(CrtAccountFormPanel);
        CrtAccountFormPanel.setLayout(CrtAccountFormPanelLayout);
        CrtAccountFormPanelLayout.setHorizontalGroup(
            CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrtAccountFormPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrtAccountFormPanelLayout.createSequentialGroup()
                        .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(examsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chooseExamLabel))
                            .addComponent(normalOptBtn))
                        .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CrtAccountFormPanelLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(weightedOptBtn))
                            .addGroup(CrtAccountFormPanelLayout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(weightField)
                                    .addComponent(weightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))))
                        .addGap(117, 117, 117))
                    .addGroup(CrtAccountFormPanelLayout.createSequentialGroup()
                        .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CrtAccountFormPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(createNewAccBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(minAverAppLabel)
                                        .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(totalOfExamsField, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(subjectField, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(teacherField, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(confirmPswField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(totalOfExamsLabel)
                                            .addComponent(subjectLabel)
                                            .addComponent(teacherLabel)
                                            .addComponent(nameLabel)
                                            .addComponent(selectLabel)))))
                            .addGroup(CrtAccountFormPanelLayout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(backBtn)))
                        .addGap(29, 29, 29))))
        );
        CrtAccountFormPanelLayout.setVerticalGroup(
            CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrtAccountFormPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(loginLabel)
                .addGap(26, 26, 26)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(teacherLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacherField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subjectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjectField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalOfExamsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalOfExamsField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(minAverAppLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPswField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CrtAccountFormPanelLayout.createSequentialGroup()
                        .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weightedOptBtn)
                            .addComponent(normalOptBtn))
                        .addGap(18, 18, 18)
                        .addComponent(chooseExamLabel))
                    .addComponent(weightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(examsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createNewAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtn)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addComponent(CrtAccountFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogoImgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogoImgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CrtAccountFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void teacherFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherFieldActionPerformed

    private void subjectFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectFieldActionPerformed

    private void weightedOptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightedOptBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightedOptBtnActionPerformed

    private void createNewAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewAccBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createNewAccBtnActionPerformed

    private void normalOptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalOptBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_normalOptBtnActionPerformed

    private void examsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examsComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CrtAccountFormPanel;
    private javax.swing.JPanel LogoImgPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel chooseExamLabel;
    private javax.swing.JPasswordField confirmPswField;
    private javax.swing.JButton createNewAccBtn;
    private javax.swing.JLabel crtAccountLink;
    private javax.swing.JComboBox<String> examsComboBox;
    private javax.swing.JLabel imgWrapperLabel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel minAverAppLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JRadioButton normalOptBtn;
    private javax.swing.JLabel selectLabel;
    private javax.swing.JTextField subjectField;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JTextField teacherField;
    private javax.swing.JLabel teacherLabel;
    private javax.swing.JPasswordField totalOfExamsField;
    private javax.swing.JLabel totalOfExamsLabel;
    private javax.swing.JLabel txtLabel;
    private javax.swing.ButtonGroup typeUserBtnGroup;
    private javax.swing.JTextField weightField;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JRadioButton weightedOptBtn;
    // End of variables declaration//GEN-END:variables
}
