/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Cursor;

/**
 *
 * @author USER
 */
public class CreateAccountView extends javax.swing.JPanel {

    /**
     * Creates new form CreateAccountView
     */
    public CreateAccountView() {
        initComponents();
        
        //Setting cursor pointer
        Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        crtAccountLink.setCursor(cursor);
        singInLink.setCursor(cursor);
        createNewAccBtn.setCursor(cursor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeUserBtnGroup = new javax.swing.ButtonGroup();
        crtAccountLink = new javax.swing.JLabel();
        txtLabel = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        LogoImgPanel = new javax.swing.JPanel();
        imgWrapperLabel = new javax.swing.JLabel();
        CrtAccountFormPanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        emailAddresLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        confirmPswField = new javax.swing.JPasswordField();
        txtLabel1 = new javax.swing.JLabel();
        confPasswordLabel = new javax.swing.JLabel();
        StudentOptBtn = new javax.swing.JRadioButton();
        txtLabel2 = new javax.swing.JLabel();
        teacherOptnBtn = new javax.swing.JRadioButton();
        createNewAccBtn = new javax.swing.JButton();
        singInLink = new javax.swing.JLabel();
        txtLabel3 = new javax.swing.JLabel();

        crtAccountLink.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        crtAccountLink.setForeground(new java.awt.Color(88, 44, 169));
        crtAccountLink.setText("Create an Account");
        crtAccountLink.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtLabel.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtLabel.setForeground(new java.awt.Color(0, 0, 0));
        txtLabel.setText("Not registered yet?");

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 800));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        LogoImgPanel.setBackground(new java.awt.Color(255, 255, 255));

        imgWrapperLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/crtAccImg.png"))); // NOI18N

        javax.swing.GroupLayout LogoImgPanelLayout = new javax.swing.GroupLayout(LogoImgPanel);
        LogoImgPanel.setLayout(LogoImgPanelLayout);
        LogoImgPanelLayout.setHorizontalGroup(
            LogoImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgWrapperLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LogoImgPanelLayout.setVerticalGroup(
            LogoImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgWrapperLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CrtAccountFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        loginLabel.setFont(new java.awt.Font("Arial", 0, 44)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(42, 8, 69));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Create your account");

        firstNameField.setBackground(new java.awt.Color(159, 107, 255));
        firstNameField.setBorder(null);
        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        firstNameLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(42, 8, 69));
        firstNameLabel.setText("First Name:");

        usernameField.setBackground(new java.awt.Color(159, 107, 255));
        usernameField.setBorder(null);
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(42, 8, 69));
        usernameLabel.setText("Username:");

        emailField.setBackground(new java.awt.Color(159, 107, 255));
        emailField.setBorder(null);
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        emailAddresLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        emailAddresLabel.setForeground(new java.awt.Color(42, 8, 69));
        emailAddresLabel.setText("Email address:");

        passwordLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(42, 8, 69));
        passwordLabel.setText("Password:");

        passwordField.setBackground(new java.awt.Color(160, 108, 255));
        passwordField.setBorder(null);

        confirmPswField.setBackground(new java.awt.Color(160, 108, 255));
        confirmPswField.setBorder(null);

        txtLabel1.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        txtLabel1.setForeground(new java.awt.Color(42, 8, 69));
        txtLabel1.setText("Are you:");

        confPasswordLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        confPasswordLabel.setForeground(new java.awt.Color(42, 8, 69));
        confPasswordLabel.setText("Confirm password:");

        StudentOptBtn.setBackground(new java.awt.Color(40, 20, 77));
        typeUserBtnGroup.add(StudentOptBtn);
        StudentOptBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        StudentOptBtn.setForeground(new java.awt.Color(40, 20, 77));
        StudentOptBtn.setText("Student");
        StudentOptBtn.setBorder(null);
        StudentOptBtn.setOpaque(false);
        StudentOptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentOptBtnActionPerformed(evt);
            }
        });

        txtLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtLabel2.setForeground(new java.awt.Color(40, 20, 77));
        txtLabel2.setText("or");
        txtLabel2.setToolTipText("");

        teacherOptnBtn.setBackground(new java.awt.Color(40, 20, 77));
        typeUserBtnGroup.add(teacherOptnBtn);
        teacherOptnBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        teacherOptnBtn.setForeground(new java.awt.Color(40, 20, 77));
        teacherOptnBtn.setText("Teacher");
        teacherOptnBtn.setBorder(null);
        teacherOptnBtn.setOpaque(false);

        createNewAccBtn.setBackground(new java.awt.Color(88, 44, 169));
        createNewAccBtn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        createNewAccBtn.setForeground(new java.awt.Color(255, 255, 255));
        createNewAccBtn.setText("CREATE NEW");
        createNewAccBtn.setBorder(null);
        createNewAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewAccBtnActionPerformed(evt);
            }
        });

        singInLink.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        singInLink.setForeground(new java.awt.Color(88, 44, 169));
        singInLink.setText("Sing in");
        singInLink.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtLabel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtLabel3.setForeground(new java.awt.Color(0, 0, 0));
        txtLabel3.setText("Already have an account?");

        javax.swing.GroupLayout CrtAccountFormPanelLayout = new javax.swing.GroupLayout(CrtAccountFormPanel);
        CrtAccountFormPanel.setLayout(CrtAccountFormPanelLayout);
        CrtAccountFormPanelLayout.setHorizontalGroup(
            CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrtAccountFormPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(createNewAccBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(confPasswordLabel)
                        .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLabel1)
                            .addComponent(passwordField)
                            .addComponent(passwordLabel)
                            .addComponent(emailField)
                            .addComponent(emailAddresLabel)
                            .addComponent(usernameField)
                            .addComponent(usernameLabel)
                            .addComponent(firstNameField)
                            .addComponent(firstNameLabel)
                            .addComponent(confirmPswField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))))
                .addGap(29, 29, 29))
            .addGroup(CrtAccountFormPanelLayout.createSequentialGroup()
                .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrtAccountFormPanelLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(teacherOptnBtn)
                        .addGap(47, 47, 47)
                        .addComponent(txtLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(StudentOptBtn))
                    .addGroup(CrtAccountFormPanelLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(txtLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(singInLink)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CrtAccountFormPanelLayout.setVerticalGroup(
            CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrtAccountFormPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(loginLabel)
                .addGap(26, 26, 26)
                .addComponent(firstNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailAddresLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPswField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentOptBtn)
                    .addComponent(txtLabel2)
                    .addComponent(teacherOptnBtn))
                .addGap(30, 30, 30)
                .addComponent(createNewAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLabel3)
                    .addComponent(singInLink))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addComponent(CrtAccountFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogoImgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogoImgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CrtAccountFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void StudentOptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentOptBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentOptBtnActionPerformed

    private void createNewAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewAccBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createNewAccBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CrtAccountFormPanel;
    private javax.swing.JPanel LogoImgPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JRadioButton StudentOptBtn;
    private javax.swing.JLabel confPasswordLabel;
    private javax.swing.JPasswordField confirmPswField;
    private javax.swing.JButton createNewAccBtn;
    private javax.swing.JLabel crtAccountLink;
    private javax.swing.JLabel emailAddresLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel imgWrapperLabel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel singInLink;
    private javax.swing.JRadioButton teacherOptnBtn;
    private javax.swing.JLabel txtLabel;
    private javax.swing.JLabel txtLabel1;
    private javax.swing.JLabel txtLabel2;
    private javax.swing.JLabel txtLabel3;
    private javax.swing.ButtonGroup typeUserBtnGroup;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
