/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author alunolages
 */
public class ScheduleExamView extends javax.swing.JPanel {

    /**
     * Creates new form ScheduleExamView
     */
    public ScheduleExamView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loginLabel2 = new javax.swing.JLabel();
        CrtAccountFormPanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        emailAddresLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        confirmPswField = new javax.swing.JPasswordField();
        txtLabel1 = new javax.swing.JLabel();
        confPasswordLabel = new javax.swing.JLabel();
        StudentOptBtn = new javax.swing.JRadioButton();
        txtLabel2 = new javax.swing.JLabel();
        teacherOptnBtn = new javax.swing.JRadioButton();
        createNewAccBtn = new javax.swing.JButton();
        singInLink = new javax.swing.JLabel();
        txtLabel3 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        loginLabel3 = new javax.swing.JLabel();
        teacherField = new javax.swing.JTextField();
        teacherLabel = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        subjectLabel = new javax.swing.JLabel();
        subjectComboBox = new javax.swing.JComboBox<>();
        numQuestField = new javax.swing.JTextField();
        numQuestionLabel = new javax.swing.JLabel();
        valueOfEachField = new javax.swing.JTextField();
        valEachQuestLabel = new javax.swing.JLabel();
        totalSquoreField = new javax.swing.JTextField();
        totalSquoreLabel = new javax.swing.JLabel();
        warnStudentsField = new javax.swing.JTextField();
        warningForStudentsLabel = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sideMenusideMenuImg.png"))); // NOI18N

        loginLabel2.setFont(new java.awt.Font("Arial", 0, 44)); // NOI18N
        loginLabel2.setForeground(new java.awt.Color(42, 8, 69));
        loginLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loginLabel2.setText("Overview");

        CrtAccountFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        loginLabel.setFont(new java.awt.Font("Arial", 0, 44)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(42, 8, 69));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Create your account");

        firstNameField.setBackground(new java.awt.Color(159, 107, 255));
        firstNameField.setBorder(null);
        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        firstNameLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(42, 8, 69));
        firstNameLabel.setText("First Name:");

        usernameField.setBackground(new java.awt.Color(159, 107, 255));
        usernameField.setBorder(null);
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(42, 8, 69));
        usernameLabel.setText("Username:");

        emailField.setBackground(new java.awt.Color(159, 107, 255));
        emailField.setBorder(null);
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        emailAddresLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        emailAddresLabel.setForeground(new java.awt.Color(42, 8, 69));
        emailAddresLabel.setText("Email address:");

        passwordLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(42, 8, 69));
        passwordLabel.setText("Password:");

        passwordField.setBackground(new java.awt.Color(160, 108, 255));
        passwordField.setBorder(null);

        confirmPswField.setBackground(new java.awt.Color(160, 108, 255));
        confirmPswField.setBorder(null);

        txtLabel1.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        txtLabel1.setForeground(new java.awt.Color(42, 8, 69));
        txtLabel1.setText("Are you:");

        confPasswordLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        confPasswordLabel.setForeground(new java.awt.Color(42, 8, 69));
        confPasswordLabel.setText("Confirm password:");

        StudentOptBtn.setBackground(new java.awt.Color(40, 20, 77));
        StudentOptBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        StudentOptBtn.setForeground(new java.awt.Color(40, 20, 77));
        StudentOptBtn.setText("Student");
        StudentOptBtn.setBorder(null);
        StudentOptBtn.setOpaque(false);
        StudentOptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentOptBtnActionPerformed(evt);
            }
        });

        txtLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtLabel2.setForeground(new java.awt.Color(40, 20, 77));
        txtLabel2.setText("or");
        txtLabel2.setToolTipText("");

        teacherOptnBtn.setBackground(new java.awt.Color(40, 20, 77));
        teacherOptnBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        teacherOptnBtn.setForeground(new java.awt.Color(40, 20, 77));
        teacherOptnBtn.setText("Teacher");
        teacherOptnBtn.setBorder(null);
        teacherOptnBtn.setOpaque(false);

        createNewAccBtn.setBackground(new java.awt.Color(88, 44, 169));
        createNewAccBtn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        createNewAccBtn.setForeground(new java.awt.Color(255, 255, 255));
        createNewAccBtn.setText("CREATE NEW");
        createNewAccBtn.setBorder(null);
        createNewAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewAccBtnActionPerformed(evt);
            }
        });

        singInLink.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        singInLink.setForeground(new java.awt.Color(88, 44, 169));
        singInLink.setText("Sing in");
        singInLink.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtLabel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtLabel3.setText("Already have an account?");

        javax.swing.GroupLayout CrtAccountFormPanelLayout = new javax.swing.GroupLayout(CrtAccountFormPanel);
        CrtAccountFormPanel.setLayout(CrtAccountFormPanelLayout);
        CrtAccountFormPanelLayout.setHorizontalGroup(
            CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrtAccountFormPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(createNewAccBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(confPasswordLabel)
                        .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLabel1)
                            .addComponent(passwordField)
                            .addComponent(passwordLabel)
                            .addComponent(emailField)
                            .addComponent(emailAddresLabel)
                            .addComponent(usernameField)
                            .addComponent(usernameLabel)
                            .addComponent(firstNameField)
                            .addComponent(firstNameLabel)
                            .addComponent(confirmPswField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))))
                .addGap(29, 29, 29))
            .addGroup(CrtAccountFormPanelLayout.createSequentialGroup()
                .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrtAccountFormPanelLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(teacherOptnBtn)
                        .addGap(47, 47, 47)
                        .addComponent(txtLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(StudentOptBtn))
                    .addGroup(CrtAccountFormPanelLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(txtLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(singInLink)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CrtAccountFormPanelLayout.setVerticalGroup(
            CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrtAccountFormPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(loginLabel)
                .addGap(26, 26, 26)
                .addComponent(firstNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailAddresLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPswField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentOptBtn)
                    .addComponent(txtLabel2)
                    .addComponent(teacherOptnBtn))
                .addGap(30, 30, 30)
                .addComponent(createNewAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CrtAccountFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLabel3)
                    .addComponent(singInLink))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(241, 234, 255));

        MainPanel.setBackground(new java.awt.Color(241, 234, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sideMenusideMenuImg.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(241, 234, 255));

        loginLabel3.setFont(new java.awt.Font("Arial", 0, 44)); // NOI18N
        loginLabel3.setForeground(new java.awt.Color(42, 8, 69));
        loginLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loginLabel3.setText("Schedule an Exam");

        teacherField.setBackground(new java.awt.Color(158, 107, 255));
        teacherField.setBorder(null);
        teacherField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherFieldActionPerformed(evt);
            }
        });

        teacherLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        teacherLabel.setForeground(new java.awt.Color(42, 8, 69));
        teacherLabel.setText("Teacher:");

        dateField.setBackground(new java.awt.Color(158, 107, 255));
        dateField.setBorder(null);
        dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldActionPerformed(evt);
            }
        });

        dateLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(42, 8, 69));
        dateLabel.setText("Date:");

        subjectLabel.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        subjectLabel.setForeground(new java.awt.Color(42, 8, 69));
        subjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subjectLabel.setText("Subject:");

        subjectComboBox.setBackground(new java.awt.Color(160, 108, 255));
        subjectComboBox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        subjectComboBox.setForeground(new java.awt.Color(255, 255, 255));
        subjectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class 1", "Class 2", "Class 3", "Class 4" }));
        subjectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectComboBoxActionPerformed(evt);
            }
        });

        numQuestField.setBackground(new java.awt.Color(158, 107, 255));
        numQuestField.setBorder(null);
        numQuestField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numQuestFieldActionPerformed(evt);
            }
        });

        numQuestionLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        numQuestionLabel.setForeground(new java.awt.Color(42, 8, 69));
        numQuestionLabel.setText("Number of questions:");

        valueOfEachField.setBackground(new java.awt.Color(158, 107, 255));
        valueOfEachField.setBorder(null);
        valueOfEachField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueOfEachFieldActionPerformed(evt);
            }
        });

        valEachQuestLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        valEachQuestLabel.setForeground(new java.awt.Color(42, 8, 69));
        valEachQuestLabel.setText("Value of each question:");

        totalSquoreField.setBackground(new java.awt.Color(158, 107, 255));
        totalSquoreField.setBorder(null);
        totalSquoreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalSquoreFieldActionPerformed(evt);
            }
        });

        totalSquoreLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        totalSquoreLabel.setForeground(new java.awt.Color(42, 8, 69));
        totalSquoreLabel.setText("Total Squore:");

        warnStudentsField.setBackground(new java.awt.Color(158, 107, 255));
        warnStudentsField.setBorder(null);
        warnStudentsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warnStudentsFieldActionPerformed(evt);
            }
        });

        warningForStudentsLabel.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        warningForStudentsLabel.setForeground(new java.awt.Color(42, 8, 69));
        warningForStudentsLabel.setText("Warning for students:");

        loginBtn.setBackground(new java.awt.Color(88, 44, 169));
        loginBtn.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("CREATE EXAM");
        loginBtn.setBorder(null);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        backBtn.setForeground(new java.awt.Color(88, 44, 169));
        backBtn.setText("Cancel All");
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teacherLabel)
                            .addComponent(teacherField, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateLabel)
                            .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(loginLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(warnStudentsField)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(warningForStudentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(numQuestionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(subjectLabel)
                                        .addComponent(numQuestField)))
                                .addGap(95, 95, 95)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(valEachQuestLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valueOfEachField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalSquoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalSquoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(backBtn)
                                .addGap(18, 18, 18)
                                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(loginLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(teacherLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teacherField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(subjectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numQuestionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numQuestField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(valEachQuestLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueOfEachField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(totalSquoreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalSquoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(warningForStudentsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warnStudentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void StudentOptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentOptBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentOptBtnActionPerformed

    private void createNewAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewAccBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createNewAccBtnActionPerformed

    private void teacherFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherFieldActionPerformed

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFieldActionPerformed

    private void subjectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectComboBoxActionPerformed

    private void numQuestFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numQuestFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numQuestFieldActionPerformed

    private void valueOfEachFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueOfEachFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueOfEachFieldActionPerformed

    private void totalSquoreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalSquoreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalSquoreFieldActionPerformed

    private void warnStudentsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warnStudentsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warnStudentsFieldActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CrtAccountFormPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JRadioButton StudentOptBtn;
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel confPasswordLabel;
    private javax.swing.JPasswordField confirmPswField;
    private javax.swing.JButton createNewAccBtn;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel emailAddresLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel loginLabel2;
    private javax.swing.JLabel loginLabel3;
    private javax.swing.JTextField numQuestField;
    private javax.swing.JLabel numQuestionLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel singInLink;
    private javax.swing.JComboBox<String> subjectComboBox;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JTextField teacherField;
    private javax.swing.JLabel teacherLabel;
    private javax.swing.JRadioButton teacherOptnBtn;
    private javax.swing.JTextField totalSquoreField;
    private javax.swing.JLabel totalSquoreLabel;
    private javax.swing.JLabel txtLabel1;
    private javax.swing.JLabel txtLabel2;
    private javax.swing.JLabel txtLabel3;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel valEachQuestLabel;
    private javax.swing.JTextField valueOfEachField;
    private javax.swing.JTextField warnStudentsField;
    private javax.swing.JLabel warningForStudentsLabel;
    // End of variables declaration//GEN-END:variables
}
